### ISSUE TITLE
"Unable to get a feature report"

### ISSUE THREAD

**Issue by ineedcoffee** [csujedihy/LG-Ultrafine-Brightness#1]
Confirmed windows 10 detected speaker, webcam and usb hub.  Running windows 10 pro.  But unable to adjust brightness

**Comment by csujedihy** [comment]
Try this one. I think the USB library is sort of buggy.
https://github.com/unknownzerx/lguf-brightness

**Comment by ineedcoffee** [comment]
Not sure how to compile a CPP file.  Any way to improve the USB library on your end.  My eyes are starting to hurt after squinting at the monitor.

**Comment by csujedihy** [comment]
I do not know how to improve. It just happens to work on my computer.
