### ISSUE TITLE
Added a friendly fork of your version which works on Windows 10 @ 20190407

### ISSUE THREAD

**Issue by yo1995** [csujedihy/LG-Ultrafine-Brightness#10]
https://github.com/yo1995/Daily_GUI_Tools/tree/master/Tool_LG-Ultrafine-brightness

Please feel free to add this link to Readme if useful. Made it work with mine.
😄

**Comment by yo1995** [comment]
also add a GUI version in this repo. if you find it useful, please give me a ⭐️

**Comment by jayhding** [comment]
@yo1995 It works for me on Windows 10 Home build 1809, thanks very much!
