### ISSUE TITLE
Unable to get a feature report. The parameter is incorrect.

### ISSUE THREAD

**Issue by zcmcc** [csujedihy/LG-Ultrafine-Brightness#12]
Will show current brightness in the application window, and increment up and down, but does not actually change brightness.

**Comment by csujedihy** [comment]
I am not able to help since I don't have this monitor anymore.

**Comment by csujedihy** [comment]
Maybe try this?

https://github.com/yo1995/Daily_GUI_Tools/tree/master/Tool_LG-Ultrafine-brightness

**Comment by zcmcc** [comment]
Really appreciate you taking time to reply.

I’ll try out the link.
