### ISSUE TITLE
"Got parameter is incorrect" after certain driver updates.

### ISSUE THREAD

**Issue by ewolam** [csujedihy/LG-Ultrafine-Brightness#13]
Hi. I have tried your code on windows 10 1903 version. It used to work, but I got "The parameter is incorrect" error after certain driver update. Somehow, it broke. Would you revise the code again? 
The Linux version of this project, however, works for the same computer after I switch to Linux. Not sure which Windows update broke your app.

**Comment by ewolam** [comment]
By the way, the error is casued by "Unable to get a feature report".

**Comment by csujedihy** [comment]
Unfortunately, I don't have a LG UF monitor anymore.

You can try this one: https://github.com/shakespark/LG-Ultrafine-Brightness
It enumerates device tree to find the correct device which mine does not do.

**Comment by csujedihy** [comment]
Please report back if you tried that repro then I can make that change upstream.

**Comment by ascarter** [comment]
@csujedihy the changes in @shakespark's repo worked for me on current version of Windows 10. Recommend asking for a PR and merging.

Thanks!
