### ISSUE TITLE
LG stops working after windows (unrelated to tool), any idea?

### ISSUE THREAD

**Issue by hannesoid** [csujedihy/LG-Ultrafine-Brightness#15]
Hi @csujedihy, 

I was just wondering if you have some secret expert knowledge or ideas.

I just connected my LG Ultrafine 5k to a windows notebook for the first time.
I then connected it back to my mac and since then, it doesn't work on mac anymore.
The mac freezes until the LG is unplugged again, and the screen remains dark.

Do you have any theories?
I was looking up a way to adjust the brightness and found your repo, maybe you have experienced this.

Feel free to close this issue if you can't help. best regards!

**Comment by csujedihy** [comment]
Sorry, no idea.
