### ISSUE TITLE
Complied and it works! But how to...

### ISSUE THREAD

**Issue by Hochiss** [csujedihy/LG-Ultrafine-Brightness#16]
make it resident since boot, integrated into system -wide hotkey to adjust brightness? e.g. adjust which monitor the mouse locate and use F5/F6 to adjust, like native WinX?

many thanks for sharing your project!

**Comment by csujedihy** [comment]
It does not have this feature. Feel free to implement it and send a PR.

I don't have a Ultrafine momitor anymore.
