### ISSUE TITLE
Win10 环境下报错

### ISSUE THREAD

**Issue by zhangzhanqicixi** [csujedihy/LG-Ultrafine-Brightness#2]
1. 打开sln文件
2. 选择x64，release
3. build

打开LG-Ultrafine-Brightness.exe就报错了
“由于找不到hidpapi.dll，无法继续执行代码。重新安装程序可能会解决此问题”

。。。楼主有这个闲心帮我看看嘛 = =

**Comment by csujedihy** [comment]
下载我打包好的二进制吧。
