### ISSUE TITLE
"Unable to get a feature report"

### ISSUE THREAD

**Issue by adam-lee** [csujedihy/LG-Ultrafine-Brightness#3]
On my 4K version of the display, I can't seem to get this working on the latest Windows 10 Pro even with admin privilege: 

Unable to get a feature report.
The parameter is incorrect.Press '-' or '=' to adjust brightness.
Press '[' or: ']' to fine tune.
Press 'p' to use the minimum brightness
Press '\' to use the maximum brightness
Press 'q' to quit.
Current brightness = 0

Has anyone seen this?

**Comment by ionantonak** [comment]
I have the same problem, running on a gtx1080 with a gc alpine ridge card

**Comment by csujedihy** [comment]
I have no idea why it does not work on your PC. You should try https://github.com/unknownzerx/lguf-brightness. IMO, it depends on the firmware version of your LG 4k/5k.

**Comment by jayhding** [comment]
@adam-lee andd @ionantonak , please have a try on https://github.com/csujedihy/LG-Ultrafine-Brightness/issues/10

I had same issue as yours and https://github.com/yo1995/Daily_GUI_Tools/tree/master/Tool_LG-Ultrafine-brightness solved my problem
