### ISSUE TITLE
Unable to get a feature report.

### ISSUE THREAD

**Issue by dvaldivia** [csujedihy/LG-Ultrafine-Brightness#4]
I'm getting an issue where I cannot change the brightness and get error `Unable to get a feature report.`

would you happen to know what version of the Visual C++ distributable is needed?

Thanks for your hard work

**Comment by daniel-chenery** [comment]
Same error here :/

**Comment by csujedihy** [comment]
This tool is busted for now. I guess LG upgrades the firmware and changes the format of the feature report. I will look into this when I have time.
