### ISSUE TITLE
"Data error (cyclic redundancy check)" from Hidapi

### ISSUE THREAD

**Issue by Ytmndissue** [csujedihy/LG-Ultrafine-Brightness#5]
This error may be related to the other closed issues regarding a possible firmware update, but it could just be something specific to my end. I'm running Windows 7 64bit and have both tested your version, and my compiled version using Visual Studio 2017 (as well as compiling Hidapi from the latest Github source.)

Upon starting the program, I get the "unable to get/set" error, as well as a "Data error (cyclic redundancy check)" error which is passed from Hidapi itself. Windows has a generic driver installed for it as "USB Input Device," and the monitor is working without a single issue. I just cannot really "talk" to the monitor to change the brightness.

Could this also be related to the firmware update? Or is this just something on my end?

**Comment by Ytmndissue** [comment]
Hmm, I'm reading up on this error and it sounds like this is related to passing or receiving an unexpectedly small or large amount of data (in other words, something like passing in an array that is larger than expected, or so forth.)

This definitely sounds like the firmware was changed and the Ultrafine 4k isn't like the way HIDAPI is talking to it...

I'd whip out Wireshark and re-reverse engineer it myself, but this computer is purely Windows (never was a mac, and no way to legitimately use boot camp to initiate communication with it.)

Looks like it's called a retina display for a reason, it's gonna burn out my retinas lol

**Comment by csujedihy** [comment]
Did you purchase your LG 4K recently? If you don't have a Mac, you are unable to figure out what is passed to the device. I sold my Mac several months ago and cannot do this re-reverse engineering as well :(

Oh, Hackintosh might work.

**Comment by Ytmndissue** [comment]
It was purchased off of someone on Ebay who purchased it fairly recently, so yeah, it's probably got the same issue as the others.

I don't have the time to put together a Hackintosh sadly. 

The only solution I can come up with might be to install a recent version of OSX on a VM, and use the VMWare USB service to point the monitor to the VM and capture it that way. There's a lot of 'ifs' there still... I don't really have the time to do this either, but I might if I get bored enough.

VMWare can be unlocked to support OSX and I've done it in the past, still isn't a walk in the park though.

**Comment by csujedihy** [comment]
I will also try it if I have the time. Thanks!
