### ISSUE TITLE
Any plans for a Linux release?

### ISSUE THREAD

**Issue by jni** [csujedihy/LG-Ultrafine-Brightness#7]

**Comment by csujedihy** [comment]
You should check if it works in Windows or not. It doesn't work for the latest firmware version as mentioned by users.

**Comment by Ytmndissue** [comment]
The bulk of the program is just sending commands to HIDAPI, and it sounds like this is also available on Linux as well (so you should be able to compile/use it.) You might have to modify some things, such as the usage of Conio.h (or if there are MS specific data types used,) but otherwise, the program is fairly simple.

The issue now is that the Ultrafines expect different communication as of the latest firmware update, it will have to be reverse engineered again.

**Comment by jni** [comment]
Thanks for your comments, @csujedihy and @Ytmndissue! I'm a complete noob in this area, but I'll take your encouragement on board and try to compile and run in the next few days. I'll report back here.

What's the process for reverse engineering? LG really don't publish a spec on this? *facepalm*

**Comment by Ytmndissue** [comment]
Reverse engineering will require a fully up to date OSX computer connected to a recent or up to date firmware revision of an Ultrafine monitor, and you will need to capture the USB packets between the two (probably using Wireshark, I think they provide a USB capture mode now.)

I'd be monitoring ambient packet exchange, as well as packet exchange during changing brightness, adjusting the color gamut (I have a hunch the most recent version of these monitors actually lets you select color modes or adjust the LUT,) as well as other operations like updating the firmware and so forth.

This is a lot of data, so unless you were highly interested, you'd only need to pay attention to the brightness packets. Then I'd compare these new packets to the structure and values of the ones constructed in the program.

LG probably just changed the size, or the structure of them and minimal modding would be needed. On the other hand, they could have gone all out and might have implemented encryption (which would make disassembling this way more difficult.)

**Comment by jni** [comment]
@Ytmndissue hmm, on the macOS GUI of Wireshark it was not obvious how to sniff USB. Any tips?

Regarding compilation, sorry but my C++ is very rusty... the only things in main.cpp that needed modification were:

```
 $ diff main.cpp main-linux.cpp 
3c3
< #include <conio.h>
---
> #include <cstdio>
114c114
<         int c = _getch();
---
>         int c = getchar();
```

but now I am failing to link to HIDAPI:

```
 $ gcc main-linux.cpp 
/tmp/ccGGCcA8.o: In function `get_brightness(hid_device_*)':
main-linux.cpp:(.text+0x18e): undefined reference to `hid_get_feature_report'
main-linux.cpp:(.text+0x1af): undefined reference to `hid_error'
/tmp/ccGGCcA8.o: In function `set_brightness(hid_device_*, unsigned short)':
main-linux.cpp:(.text+0x248): undefined reference to `hid_send_feature_report'
main-linux.cpp:(.text+0x269): undefined reference to `hid_error'
/tmp/ccGGCcA8.o: In function `main':
main-linux.cpp:(.text+0x2a8): undefined reference to `hid_init'
main-linux.cpp:(.text+0x2cf): undefined reference to `hid_open'
main-linux.cpp:(.text+0x4b7): undefined reference to `hid_close'
main-linux.cpp:(.text+0x4bc): undefined reference to `hid_exit'
/tmp/ccGGCcA8.o: In function `__static_initialization_and_destruction_0(int, int)':
main-linux.cpp:(.text+0x50c): undefined reference to `std::ios_base::Init::Init()'
main-linux.cpp:(.text+0x521): undefined reference to `std::ios_base::Init::~Init()'
/tmp/ccGGCcA8.o: In function `__gnu_cxx::new_allocator<unsigned short>::deallocate(unsigned short*, unsigned long)':
main-linux.cpp:(.text._ZN9__gnu_cxx13new_allocatorItE10deallocateEPtm[_ZN9__gnu_cxx13new_allocatorItE10deallocateEPtm]+0x1c): undefined reference to `operator delete(void*)'
/tmp/ccGGCcA8.o: In function `__gnu_cxx::new_allocator<unsigned short>::allocate(unsigned long, void const*)':
main-linux.cpp:(.text._ZN9__gnu_cxx13new_allocatorItE8allocateEmPKv[_ZN9__gnu_cxx13new_allocatorItE8allocateEmPKv]+0x2c): undefined reference to `std::__throw_bad_alloc()'
main-linux.cpp:(.text._ZN9__gnu_cxx13new_allocatorItE8allocateEmPKv[_ZN9__gnu_cxx13new_allocatorItE8allocateEmPKv]+0x3b): undefined reference to `operator new(unsigned long)'
/tmp/ccGGCcA8.o:(.data.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
```

This is after `sudo apt install libhidapi-dev` on Ubuntu 18.04, which seemed to work fine.

**Comment by csujedihy** [comment]
You need to pass a ‘-l’ to gcc to link hidapi. Try -lhidapi? If it doesn’t work, you need to figure out the name of the lib and pass it to ‘-l’.

Best regards,

Yi

**Comment by jni** [comment]
Hmmm, perhaps there is a version difference? I finally found the libs:

```
 $ ls /usr/lib/x86_64-linux-gnu/ | grep hidapi
libhidapi-hidraw.a
libhidapi-hidraw.so
libhidapi-hidraw.so.0
libhidapi-hidraw.so.0.0.0
libhidapi-libusb.a
libhidapi-libusb.so
libhidapi-libusb.so.0
libhidapi-libusb.so.0.0.0
```

But that doesn't seem to help:

```
 $ g++ -I/usr/include/hidapi/ -lhidapi-hidraw main-linux.cpp 
/tmp/ccxtzxbS.o: In function `get_brightness(hid_device_*)':
main-linux.cpp:(.text+0x18e): undefined reference to `hid_get_feature_report'
main-linux.cpp:(.text+0x1af): undefined reference to `hid_error'
/tmp/ccxtzxbS.o: In function `set_brightness(hid_device_*, unsigned short)':
main-linux.cpp:(.text+0x248): undefined reference to `hid_send_feature_report'
main-linux.cpp:(.text+0x269): undefined reference to `hid_error'
/tmp/ccxtzxbS.o: In function `main':
main-linux.cpp:(.text+0x2a8): undefined reference to `hid_init'
main-linux.cpp:(.text+0x2cf): undefined reference to `hid_open'
main-linux.cpp:(.text+0x4b7): undefined reference to `hid_close'
main-linux.cpp:(.text+0x4bc): undefined reference to `hid_exit'
collect2: error: ld returned 1 exit status
```

(The libusb version also doesn't work.)

I also tried compiling from source in [this repo](https://github.com/signal11/hidapi), apparently successfully, but still to no avail.

Also TIL that gcc doesn't automatically select the C or C++ compiler based on the file extension. :joy: 

Thanks!

**Comment by velum** [comment]
I managed to compile this project on Ubuntu 16.04, and the program runs, but it does not work. For some reason hid_get_feature_report and hid_send_feature_report return -1 which means that there was an error, and hid_error is returning null, so I don't know what the error is. I had to replace conio by curses, and replace all printf's by printw's. I have to experiment a bit more with all this. On thing this program does though when ran on Linux is to activate the ambient light sensor. As soon as I try to adjust the brightness of the screen by pressing let's say the '\' key, the light sensor gets activated, and the brightness adjusts itself in response to the room brightness. The keys don't work though. I cannot use them to adjust the brightness. And the thing with the ambien light sensor is a side effect. The program is not meant to activate it. I have no clue why it does that and why it is working fine on Windows but not on Linux. By the way, the automatic adjustment of the brightness with the light sensor is useless. It does not set the brightness of the screen to the level that is comfortable with the brightness of the room.

**Comment by velum** [comment]
@jni Have you tried `g++ -I/usr/include/hidapi/ -lhidapi-libusb main-linux.cpp `?

**Comment by jni** [comment]
@velum I'm not sure whether I tried that specific command but it's giving me the same error as before:

```
 $ g++ -I/usr/include/hidapi/ -lhidapi-libusb main-linux.cpp
/tmp/cc6IpZNq.o: In function `get_brightness(hid_device_*)':
main-linux.cpp:(.text+0x18e): undefined reference to `hid_get_feature_report'
main-linux.cpp:(.text+0x1af): undefined reference to `hid_error'
/tmp/cc6IpZNq.o: In function `set_brightness(hid_device_*, unsigned short)':
main-linux.cpp:(.text+0x248): undefined reference to `hid_send_feature_report'
main-linux.cpp:(.text+0x269): undefined reference to `hid_error'
/tmp/cc6IpZNq.o: In function `main':
main-linux.cpp:(.text+0x2a8): undefined reference to `hid_init'
main-linux.cpp:(.text+0x2cf): undefined reference to `hid_open'
main-linux.cpp:(.text+0x4b7): undefined reference to `hid_close'
main-linux.cpp:(.text+0x4bc): undefined reference to `hid_exit'
collect2: error: ld returned 1 exit status
```

Both hidraw and libusb appear to be installed:

```
libhidapi-dev/bionic,now 0.8.0~rc1+git20140818.d17db57+dfsg-2 amd64 [installed]
  Multi-Platform library for communication with HID devices (development files)

libhidapi-hidraw0/bionic,now 0.8.0~rc1+git20140818.d17db57+dfsg-2 amd64 [installed]
  Multi-Platform library for communication with HID devices (hidraw backend)

libhidapi-libusb0/bionic,now 0.8.0~rc1+git20140818.d17db57+dfsg-2 amd64 [installed]
  Multi-Platform library for communication with HID devices (libusb backend)
```

What versions do you have? Do you have notes on what steps you took till now?

**Comment by velum** [comment]
@csujedihy I was able to use your program on Windows 10, and it worked perfectly fine with my LG UltraFine 4K screen. I also managed to compile your program on Ubuntu 16.04, but on that platform (same hardware, just a different boot disk), it does not work. hid_get_feature_report returns -1. Do you have any idea why that could be?

**Comment by csujedihy** [comment]
@velum Sorry. I have no idea since I don't have a Ubuntu to test with. Can you share your steps of compiling it in Ubuntu so others can try and figure it out?

**Comment by jni** [comment]
Hi everyone,

So, @velum's report that it was working on Windows 10 reinvigorated my work. I'm happy to report some progress! (Though I am currently typing this on a very dim monitor :joy:)

First I confirmed that the program indeed works on my Windows 10 partition, and indeed it does, perfectly.

Second, regarding my error, perhaps it's due to different versions of GCC, but it was [this problem](https://stackoverflow.com/questions/15433774/hidapi-unable-to-compile-any-code-under-ubuntu): the order of the `-l` and `.o` arguments matters! :man_facepalming: 

```
g++ -I/usr/include/hidapi -c main-linux.cpp
```

works as expected, then:

```
g++ -I/usr/include/hidapi/ -lhidapi-libusb main-linux.o
```

fails as above. After checking the `.so` files with `nm` for the symbol tables to verify that those functions were indeed defined there, I thought I must be calling the linker incorrectly. And indeed the following did the trick:

```
g++ main-linux.o -I/usr/include/hidapi -lhidapi-libusb -o run
```

**sigh**

Ok, so then I tried `./run` and got:

```
unable to open device
```

Looking at [this page](https://github.com/trezor/cython-hidapi) and [this page](https://github.com/signal11/hidapi/issues/148) suggested a permissions issue, so I tried:

```
sudo ./run
```

and got the ever-so lovely prompt:

```
Unable to get a feature report.
(null)Press '-' or '=' to adjust brightness.
Press '[' or: ']' to fine tune.
Press 'p' to use the minimum brightness
Press '\' to use the maximum brightness
Press 'q' to quit.
Current brightness = 0    
```

:tada: 

I guess I'm in the same place as @velum. The difference is that (a) I am able to *decrease* the brightness no problem, but not increase it, and (b) after running the program, the light sensor is controlling the brightness — a little on the low side, but it's working! Which is interesting.

@velum do you know the correct way to set udev permissions so that I don't have to run this program as sudo?

**Comment by velum** [comment]
I got it to work on **Ubuntu 16.04**! :-) I based myself on this project and on the initial one, Here is the result: [https://github.com/velum/lguf-brightness](https://github.com/velum/lguf-brightness)

**Comment by csujedihy** [comment]
Great! I will add a link to your repo.

**Comment by jni** [comment]
Hey @velum! You should make your repo a separate repo, rather than a fork, because I can't raise any issues on your fork! This way we can stop spamming @csujedihy. =)

Anyway, specifically, it doesn't seem to work on my monitor at all. 

```
Unable to get brightness.
libusb_control_transfer error: LIBUSB_ERROR_IO (-1)
Press '-' or '=' to adjust brightness.
Press '[' or: ']' to fine tune.
Press 'p' to use the minimum brightness
Press '\' to use the maximum brightness
Press 'q' to quit.
Current brightness = 0
```
Pressing any key other than "q" results in the error "Unable to set brightness".

If you can write up how you came up with your changes for the original, I might be able to wrangle it for my monitor as well...! As I mentioned above, this repo is *almost* working for me.

To specify what I did with yours, I ran:

```
cmake .
make
```

in the same directory as your folder. Then I ran

```
sudo ./lguf_brightness
```

Did I miss anything? Any help is appreciated!

**Comment by charsi** [comment]
@velum 's repo worked perfectly for my 21.5 inch version of 4k LG ultrafine. Thanks @velum.
