### ISSUE TITLE
闪退。。。

### ISSUE THREAD

**Issue by zhangzhanqicixi** [csujedihy/LG-Ultrafine-Brightness#8]
Win10，LG Utrafine4K显示器，ASUS Z270 主板。请问有什么办法可以看到闪退原因吗？

**Comment by zhangzhanqicixi** [comment]
看到报错了。。。


C:\Users\pc\Downloads\LG-Ultrafine-Brightness-v0.1 (1)>LG-Ultrafine-Brightness.exe
unable to open device

C:\Users\pc\Downloads\LG-Ultrafine-Brightness-v0.1 (1)>pause
请按任意键继续. . .
终止批处理操作吗(Y/N)?

**Comment by csujedihy** [comment]
"unable to open device" is the reason the program exited without success. It means it couldn't find a device on your machine that matches the vendor ID and product ID. Do you have a TB3 bridge adapter installed on your PC?
