### ISSUE TITLE
not working. Unable to open device. 

### ISSUE THREAD

**Issue by karasjoh000** [csujedihy/LG-Ultrafine-Brightness#9]
I have a thunderbolt 3 card on my PC that connects to a DP port on nividia graphics card. Fails on getting handle.

**Comment by danielnmai** [comment]
Same issue. the call `hid_open(vendor_id, product_id, NULL)` always returns NULL. Please help with this.

**Comment by csujedihy** [comment]
I guess it won't work on new models. You will need to update vendor_id and product_id.
